snapshot_features:
  common:
    - n
    - gender
    - citizenship
    - education
    - family_status
    - children
    - to_work_travel_time
    - department
    - n_employers
    - occupational_hazards
  specific:
    - age
    - company_seniority
    - overall_experience
    - license_expiration
    - salary_avg
    - salary_current
    - time_since_salary_increase
    - income_6m_average
    - income_current
    - time_since_last_promotion
    - absenteeism_longterm
    - absenteeism_shortterm
    - vacation_days  # except last month?
    - overtime_longterm
    - overtime_shortterm
    - night_hours
    - leader_left
    - has_meal
    - has_insurance
    - penalties_shortterm
    - penalties_longterm