data_location:
  data_path: 'data_raw/'
  trg_path: 'data/'

#  file_name: 'seq_final.xlsx'  # check file extension
#  output_name: 'sequoia_dataset_24_add_short_service.csv'
#data:
#  region: 'Москва'
#  industry: 'Light industry'  #  Metals, Light industry

#  file_name: 'SWG_final1.xlsx'  # check file extension
#  output_name: 'swg_dataset_22_add_short_service.csv'
#data:
#  region: 'Москва'
#  industry: 'Electric'  #  Metals, Light industry

#  file_name: 'polimer.xlsx'  # check file extension
#  output_name: 'polimer_dataset_2222_add_short_service.csv'
#data:
#  region: 'Оренбург'
#  industry: 'Metals'  #  Metals, Light industry

  file_name: 'Химик_final_3y.xlsx'  # check file extension
  output_name: 'chemi_dataset_23_add_short_service_rnd.csv'
data:
  region: 'Москва'
  industry: 'Chemistry'  #  Metals, Light industry

  income_calibration: 'Inflation'  # Living wage, Inflation
  remove_short_service: False
  date_format: '%Y.%m.%d'
  data_begin_date: '01.01.2023'
  data_load_date: '01.10.2024'
time_snapshots:
  snapshot_step: 3  # months
  snapshot_min_duration: 3
  snapshot_initial_offset: 1  # should ALWAYS be >=1 because employee will get smaller salary on last month if they leave in the middle of the month
  max_snapshots_number: 2
  min_window: 2
  max_window: 5
  random_snapshot: True
options:
  forecast_horison: 12  # 'left' workers turn into 'working' if observed this long before dismissal
  remove_censored: False
required_sheets:
  basic:
    name: 'Основные данные'
    features:
      f1:
        name: '№'
        name_out: 'n'
        type: 'int'
        kind: 'common'
      f2:
        name: 'Code'  # check uniqueness
        name_out: 'code'
        type: 'str'
        kind: 'common'
      f3:
        name: 'Gender'
        name_out: 'gender'
        type: 'str'
        values: ['ж', 'Ж', 'жен', 'Жен', 'женский', 'Женский', 'м', 'М', 'муж', 'Муж', 'мужской', 'Мужской']
        kind: 'common'
      f4:
        name: 'Age'
        name_out: 'age'
        type: 'int'
        interval: [18, 100]
        kind: 'common'
      f5:
        name: 'Nationality'
        name_out: 'citizenship'
        kind: 'common'
      f6:
        name: 'Education'
        name_out: 'education'
        kind: 'common'
      f7:
        name: 'family status'
        name_out: 'family_status'
        kind: 'common'
      f8:
        name: 'kids up to 18Y'
        name_out: 'children'
        kind: 'common'
      f9:
        name: 'Employer address'
      f10:
        name: 'Job title'
        name_out: 'job_category'
        kind: 'common'
      f11:
        name: 'Hire date'
        name_out: 'recruitment_date'
        kind: 'common'
      f12:
        name: 'Date of dismissal'
        name_out: 'termination_date'
        kind: 'common'
      f13:
        name: 'Reason of dismissal'
      f14:
        name: 'Общий стаж работы'
#      f15:
#        name: 'Кол-во мест работодателей за карьеру'
#        name_out: 'n_employers'
#        kind: 'common'
      f16:
        name: 'Category of harmfulness'
        name_out: 'occupational_hazards'
        kind: 'common'
      f17:
        name: 'Date of work permite expiration'
      f18:
        name: 'Seniority'
        name_out: 'seniority'
        kind: 'common'
      f19:
        name: 'Status'
        name_out: 'status'
        kind: 'common'
      f20:
        name: 'Birth date'
        name_out: 'birth_date'
        kind: 'common'
      f21:
        name: 'City'
        name_out: 'city'
        kind: 'common'
      f22:
        name: 'City_population'
        name_out: 'city_population'
        kind: 'common'
      f23:
        name: 'Department'
        name_out: 'department'
        kind: 'common'
      f24:
        name: 'Total seniority'
        name_out: 'total_seniority'
        kind: 'common'
      f25:
        name: 'Region'
        name_out: 'region'
        kind: 'common'
      f26:
        name: 'Industry kind'
        name_out: 'industry_kind_internal'
        kind: 'common'
#  salary:
#    name: 'Оплата труда'
#    name_out: 'salary'
#    kind: ['time_series', 'events']
#    features:
#      f1:
#        name: '№'
#        type: 'int'
#      f2:
#        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
#        type: 'str'
#      f3:
#        name: 'Январь'
#        type: 'str'
#      f4:
#        name: 'Февраль'
#      f5:
#        name: 'Март'
#      f6:
#        name: 'Апрель'
#      f7:
#        name: 'Май'
#      f8:
#        name: 'Июнь'
#      f9:
#        name: 'Июль'
#      f10:
#        name: 'Август'
#      f11:
#        name: 'Сентябрь'
#      f12:
#        name: 'Октябрь'
#      f13:
#        name: 'Ноябрь'
#      f14:
#        name: 'Декабрь'
  income:
    name: 'Выплаты'
    name_out: 'income'
    kind: ['time_series', 'events']
    features:
      f1:
        name: '№'
        type: 'int'
      f2:
        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
        type: 'str'
      f3:
        name: 'Январь'
        type: 'str'
      f4:
        name: 'Февраль'
      f5:
        name: 'Март'
      f6:
        name: 'Апрель'
      f7:
        name: 'Май'
      f8:
        name: 'Июнь'
      f9:
        name: 'Июль'
      f10:
        name: 'Август'
      f11:
        name: 'Сентябрь'
      f12:
        name: 'Октябрь'
      f13:
        name: 'Ноябрь'
      f14:
        name: 'Декабрь'
#  promotions:
#    name: 'Дата повышения'
#    name_out: 'days_since_promotion'
#    kind: 'events'
#    features:
#      f1:
#        name: '№'
#        type: 'int'
#      f2:
#        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
#        type: 'str'
#      f3:
#        name: 'Дата последнего повышения'
  absenteeism:
    name: 'Отсутствия'
    name_out: 'absenteeism'
    kind: 'time_series'
    features:
      f1:
        name: '№'
        type: 'int'
      f2:
        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
        type: 'str'
      f3:
        name: 'Январь'
        type: 'str'
      f4:
        name: 'Февраль'
      f5:
        name: 'Март'
      f6:
        name: 'Апрель'
      f7:
        name: 'Май'
      f8:
        name: 'Июнь'
      f9:
        name: 'Июль'
      f10:
        name: 'Август'
      f11:
        name: 'Сентябрь'
      f12:
        name: 'Октябрь'
      f13:
        name: 'Ноябрь'
      f14:
        name: 'Декабрь'
  vacation_days:
    name: 'Отпуск'
    name_out: 'vacation_days'
    kind: 'time_series'
    features:
      f1:
        name: '№'
        type: 'int'
      f2:
        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
        type: 'str'
      f3:
        name: 'Январь'
        type: 'str'
      f4:
        name: 'Февраль'
      f5:
        name: 'Март'
      f6:
        name: 'Апрель'
      f7:
        name: 'Май'
      f8:
        name: 'Июнь'
      f9:
        name: 'Июль'
      f10:
        name: 'Август'
      f11:
        name: 'Сентябрь'
      f12:
        name: 'Октябрь'
      f13:
        name: 'Ноябрь'
      f14:
        name: 'Декабрь'
  overtime:
    name: 'Сверхурочка'
    name_out: 'overtime'
    kind: 'time_series'
    features:
      f1:
        name: '№'
        type: 'int'
      f2:
        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
        type: 'str'
      f3:
        name: 'Январь'
        type: 'str'
      f4:
        name: 'Февраль'
      f5:
        name: 'Март'
      f6:
        name: 'Апрель'
      f7:
        name: 'Май'
      f8:
        name: 'Июнь'
      f9:
        name: 'Июль'
      f10:
        name: 'Август'
      f11:
        name: 'Сентябрь'
      f12:
        name: 'Октябрь'
      f13:
        name: 'Ноябрь'
      f14:
        name: 'Декабрь'
#  night_hours:
#    name: 'Количество ночных смен'
#    name_out: 'night_hours'
#    kind: 'time_series'
#    features:
#      f1:
#        name: '№'
#        type: 'int'
#      f2:
#        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
#        type: 'str'
#      f3:
#        name: 'Январь'
#        type: 'str'
#      f4:
#        name: 'Февраль'
#      f5:
#        name: 'Март'
#      f6:
#        name: 'Апрель'
#      f7:
#        name: 'Май'
#      f8:
#        name: 'Июнь'
#      f9:
#        name: 'Июль'
#      f10:
#        name: 'Август'
#      f11:
#        name: 'Сентябрь'
#      f12:
#        name: 'Октябрь'
#      f13:
#        name: 'Ноябрь'
#      f14:
#        name: 'Декабрь'
#  meal:
#    name: 'Обед'
#    name_out: 'meal'
#    features:
#      f1:
#        name: '№'
#        type: 'int'
#      f2:
#        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
#        type: 'str'
#      f3:
#        name: 'Январь'
#        type: 'str'
#      f4:
#        name: 'Февраль'
#      f5:
#        name: 'Март'
#      f6:
#        name: 'Апрель'
#      f7:
#        name: 'Май'
#      f8:
#        name: 'Июнь'
#      f9:
#        name: 'Июль'
#      f10:
#        name: 'Август'
#      f11:
#        name: 'Сентябрь'
#      f12:
#        name: 'Октябрь'
#      f13:
#        name: 'Ноябрь'
#      f14:
#        name: 'Декабрь'
#  insurance:
#    name: 'ДМС'
#    name_out: 'insurance'
#    features:
#      f1:
#        name: '№'
#        type: 'int'
#      f2:
#        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
#        type: 'str'
#      f3:
#        name: 'Январь'
#        type: 'str'
#      f4:
#        name: 'Февраль'
#      f5:
#        name: 'Март'
#      f6:
#        name: 'Апрель'
#      f7:
#        name: 'Май'
#      f8:
#        name: 'Июнь'
#      f9:
#        name: 'Июль'
#      f10:
#        name: 'Август'
#      f11:
#        name: 'Сентябрь'
#      f12:
#        name: 'Октябрь'
#      f13:
#        name: 'Ноябрь'
#      f14:
#        name: 'Декабрь'
#  penalties:
#    name: 'Взыскания'
#    name_out: 'penalties'
#    kind: 'time_series'
#    features:
#      f1:
#        name: '№'
#        type: 'int'
#      f2:
#        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
#        type: 'str'
#      f3:
#        name: 'Январь'
#        type: 'str'
#      f4:
#        name: 'Февраль'
#      f5:
#        name: 'Март'
#      f6:
#        name: 'Апрель'
#      f7:
#        name: 'Май'
#      f8:
#        name: 'Июнь'
#      f9:
#        name: 'Июль'
#      f10:
#        name: 'Август'
#      f11:
#        name: 'Сентябрь'
#      f12:
#        name: 'Октябрь'
#      f13:
#        name: 'Ноябрь'
#      f14:
#        name: 'Декабрь'
#  company_structure:
#    name: 'Структура компании'
#    name_out: 'leader_left'
#    features:
#      f1:
#        name: '№'
#        type: 'int'
#      f2:
#        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
#        type: 'str'
#      f3:
#        name: 'Подразделение'
#        type: 'str'
#      f4:
#        name: 'Прямой руководитель'
#        type: 'str'