data_location:
  data_path: 'data/'
  file_name: 'data.xlsx'  # check file extension
basic:
  snapshot_duration: 6  # months
  date_format: '%Y.%m.%d'
required_sheets:
  basic:
    name: 'Основные данные'
    features:
      f1:
        name: '№'
        name_out: 'n'
        type: 'int'
        kind: 'common'
      f2:
        name: 'ФИО / код сотрудника'  # check uniqueness
        name_out: 'code'
        type: 'str'
        kind: 'common'
      f3:
        name: 'Пол'
        name_out: 'gender'
        type: 'str'
        values: ['ж', 'Ж', 'жен', 'Жен', 'женский', 'Женский', 'м', 'М', 'муж', 'Муж', 'мужской', 'Мужской']
        kind: 'common'
      f4:
        name: 'Возраст'
        type: 'int'
        interval: [18, 100]
      f5:
        name: 'Гражданство'
        name_out: 'citizenship'
        kind: 'common'
      f6:
        name: 'Образование'
        name_out: 'education'
        kind: 'common'
      f7:
        name: 'Семейное положение'
        name_out: 'family_status'
        kind: 'common'
      f8:
        name: 'Кол-во детей'
        name_out: 'children'
        kind: 'common'
      f9:
        name: 'Адрес работы'
      f10:
        name: 'Департамент'
        name_out: 'department'
        kind: 'common'
      f11:
        name: 'Дата найма'
      f12:
        name: 'Дата увольнения'
      f13:
        name: 'Причина увольнения'
      f14:
        name: 'Общий стаж работы'
      f15:
        name: 'Кол-во мест работодателей за карьеру'
        name_out: 'n_employers'
        kind: 'common'
      f16:
        name: 'Категория вредности'
        name_out: 'occupational_hazards'
        kind: 'common'
      f17:
        name: 'Дата истечения разрешения на работу'
  salary:
    name: 'Оплата труда'
    features:
      f1:
        name: '№'
        type: 'int'
      f2:
        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
        type: 'str'
      f3:
        name: 'Январь'
        type: 'str'
      f4:
        name: 'Февраль'
      f5:
        name: 'Март'
      f6:
        name: 'Апрель'
      f7:
        name: 'Май'
      f8:
        name: 'Июнь'
      f9:
        name: 'Июль'
      f10:
        name: 'Август'
      f11:
        name: 'Сентябрь'
      f12:
        name: 'Октябрь'
      f13:
        name: 'Ноябрь'
      f14:
        name: 'Декабрь'
  income:
    name: 'Общий доход'
    features:
      f1:
        name: '№'
        type: 'int'
      f2:
        name: 'ФИО/код сотрудника'  # check they are same like on sheet 1
        type: 'str'
      f3:
        name: 'Январь'
        type: 'str'
      f4:
        name: 'Февраль'
      f5:
        name: 'Март'
      f6:
        name: 'Апрель'
      f7:
        name: 'Май'
      f8:
        name: 'Июнь'
      f9:
        name: 'Июль'
      f10:
        name: 'Август'
      f11:
        name: 'Сентябрь'
      f12:
        name: 'Октябрь'
      f13:
        name: 'Ноябрь'
      f14:
        name: 'Декабрь'